<a href="https://colab.research.google.com/github/Zaicevvv/goit-dsandml-private/blob/main/HW4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a = np.random.randint(1,10,(5,5))
print(a)

[[9 2 5 6 9]
 [6 4 3 4 3]
 [5 6 2 4 1]
 [4 4 3 7 9]
 [7 1 6 6 1]]


In [ ]:
a = np.random.random((4,4))
print(a)

[[0.20354806 0.87036848 0.09250915 0.57907478]
 [0.41141299 0.66239903 0.76399842 0.06492236]
 [0.52124772 0.62733789 0.45528992 0.64958244]
 [0.75323398 0.90899642 0.86167328 0.76962454]]


In [ ]:
a = np.random.randint(1,10,(5,))
b = np.random.randint(1,10,(5,))
print(a + b)
print(a - b)
print(a * b)

[11  9  8 14 15]
[-7  7  2  0 -3]
[18  8 15 49 54]


In [ ]:
a = np.random.randint(1,10,(7,))
b = np.random.randint(1,10,(7,))
print(np.dot(a, b))

210


In [ ]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,3))
print(np.dot(a, b))

[[11 28 16]
 [21 68 36]]


In [ ]:
a = np.random.randint(1,10,(3,3))
print(np.linalg.inv(a))

[[ 0.13953488  0.06976744 -0.08527132]
 [-0.02325581 -0.51162791  0.40310078]
 [-0.02325581  0.48837209 -0.26356589]]


In [ ]:
a = np.random.random((4,4))
print(a.T)

[[0.22686835 0.92541723 0.90595048 0.56059839]
 [0.90957958 0.5829641  0.87100204 0.9901494 ]
 [0.01820523 0.89593911 0.60711711 0.27311048]
 [0.27508699 0.18752798 0.6647294  0.43321512]]


In [ ]:
a = np.random.randint(1,10,(3,4))
b = np.random.randint(1,10,(4,))
print(np.dot(a, b))

[ 69 102 113]


In [ ]:
a = np.random.random((2,3))
b = np.random.random((3,))
print(np.dot(a, b))

[0.66051007 0.24639499]


In [ ]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))
print(a * b)

[[63 45]
 [24 45]]


In [ ]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))
print(np.dot(a, b))

[[14 91]
 [ 7 28]]


In [ ]:
a = np.random.randint(1,100,(5,5))
print(a.sum())

1375


In [ ]:
a = np.random.randint(1,10,(4,4))
b = np.random.randint(1,10,(4,4))
print(a - b)

[[ 0 -4 -1 -5]
 [ 4 -2  4 -3]
 [-4  6 -1  7]
 [-1 -1  3  0]]


In [ ]:
a = np.random.random((3,3))
b = np.sum(a, axis=1)
print(b.reshape(-1,1))

[[1.31961221]
 [1.1061344 ]
 [1.55167874]]


In [ ]:
a = np.random.randint(1, 10,(3, 4))
print(np.square(a))

[[16  4 64 81]
 [ 9 36 64 49]
 [ 9  1 36  1]]


In [3]:
a = np.random.randint(1, 50,(4,))
print(np.sqrt(a))

[6.164414   5.91607978 6.78232998 5.83095189]
