<a href="https://colab.research.google.com/github/Zaicevvv/goit-dsandml-privat/blob/main/HW4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[a % 2 != 0] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [101]:
a = np.random.randint(1,10,(6,))
print(a.reshape(2, -1))

[[8 6 7]
 [2 9 9]]


In [102]:
a = np.random.randint(1,10,(2,3))
b = np.random.randint(1,10,(2,3))
print(np.vstack((a, b)))

[[9 2 3]
 [2 6 4]
 [1 5 8]
 [2 9 1]]


In [103]:
a = np.array([1,2,3])
print(np.hstack((np.repeat(a, 3), np.tile(a, 3))))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [104]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


In [105]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(np.argsort(a)[-5:])

[18  7  3 10 15]


In [106]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
print(a[~np.isnan(a)])

[1. 2. 3. 5. 6. 7.]


In [107]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print(np.linalg.norm(a - b))

6.708203932499369


In [108]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
print(np.where(x == 1)[0][4])

8


In [20]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
un = set()
changed = []
for i in range(a.size):
  if a[i] in un:
    changed.append(True)
  else:
    changed.append(False)
  un.add(a[i])
print(np.array(changed))

[False  True False  True False False  True  True  True  True]
